[package]
name = "edition-2015"
version = "0.1.0"
authors = ["Michael Lamparski <diagonaldevice@gmail.com>"]
edition = "2015"

[[bin]]
name = "edition-2015"
path = "main.rs"

[dependencies]
newtype-ops = { path = "../.." }
